import {useState} from 'react';
import {request} from './api';
import {Suggestion} from './types';
export function AnalysisPanel({repository,branch,editable}:{repository:string;branch:string;editable:boolean}){
 const [split,setSplit]=useState('2026-01-01T12:00:00Z');const [comparison,setComparison]=useState<Record<string,unknown>|null>(null);const [evaluation,setEvaluation]=useState<{total:number;passed:number;scope:string;cases:Record<string,unknown>[]} |null>(null);const [suggestions,setSuggestions]=useState<Suggestion[]>([]);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 async function work(kind:string){setBusy(kind);setError('');try{if(kind==='compare')setComparison(await request('/api/compare?'+new URLSearchParams({split,repository,branch})));if(kind==='evaluation')setEvaluation(await request('/api/evaluation'));if(kind==='advice'){const data=await request<{suggestions:Suggestion[]}>('/api/advice?'+new URLSearchParams({repository,branch}),'POST',{consent:true});setSuggestions(data.suggestions);}}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <section className="panel"><h2>Compare and evaluate</h2><p>Split imported runs at an explicit timestamp. Reports compare observed counts, not equal-sized statistical cohorts. Missing signatures in a later sample are not proof of resolution.</p><label>Split timestamp (with timezone)<input value={split} onChange={e=>setSplit(e.target.value)}/></label><button disabled={!!busy} onClick={()=>work('compare')}>Compare samples</button>{comparison&&<pre>{JSON.stringify(comparison,null,2)}</pre>}
 <h3>AI/ML evaluation</h3><p>Run the built-in normalization diagnostic corpus: volatile timestamps and addresses should collapse, while error codes and assertion values remain distinct.</p><button className="secondary" disabled={!!busy} onClick={()=>work('evaluation')}>Run diagnostics</button>{evaluation&&<div role="status"><strong>{evaluation.passed} / {evaluation.total} cases passed</strong><p>{evaluation.scope}</p><details><summary>Show every diagnostic result</summary><pre>{JSON.stringify(evaluation.cases,null,2)}</pre></details></div>}
 <h3>Optional model investigation advice</h3><p>The core product runs offline. This optional request sends up to ten groups and two redacted excerpts per group to the operator-configured model. Suggestions are untrusted investigation ideas; they never run commands or change triage. Source quotes are checked, but recommendations still require human judgment.</p><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I approve sending the selected failure evidence to the configured provider.</label><button disabled={!editable||!consent||!!busy} onClick={()=>work('advice')}>Request advice</button>
 {suggestions.map((s,i)=><article key={i}><strong>{s.group_id}</strong><blockquote>{s.quote}</blockquote><p>{s.recommendation}</p><p className="muted">Source run: {s.run_id}</p></article>)}{busy&&<p role="status">Working: {busy}…</p>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
