import {useEffect,useState,useRef} from 'react';
import {request,setCsrf,query,download} from './api';
import {User,Report,Run,Group,Audit} from './types';
import {ImportPanel} from './ImportPanel';
import {GroupPanel} from './GroupPanel';
import {AnalysisPanel} from './AnalysisPanel';

export default function App(){
 const [user,setUser]=useState<User|null>(null);const [authMode,setAuthMode]=useState('oidc');const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [tab,setTab]=useState('board');const [repository,setRepository]=useState('');const [branch,setBranch]=useState('');const [minutes,setMinutes]=useState(10);const [report,setReport]=useState<Report|null>(null);const [runs,setRuns]=useState<Run[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [selected,setSelected]=useState<Group|null>(null);const [status,setStatus]=useState('all');const requestNumber=useRef(0);
 const editable=!!user?.roles.some(x=>['admin','reviewer'].includes(x));
 async function refresh(){const n=++requestNumber.current;setBusy(true);setError('');try{const q=query(repository,branch,minutes);const [r,list,a]=await Promise.all([request<Report>('/api/report?'+q),request<Run[]>('/api/runs?'+new URLSearchParams({repository,branch})),request<Audit[]>('/api/audit')]);if(n===requestNumber.current){setReport(r);setRuns(list);setAudit(a);setSelected(null);}}catch(e){if(n===requestNumber.current)setError((e as Error).message);}finally{if(n===requestNumber.current)setBusy(false);}}
 useEffect(()=>{let active=true;Promise.all([request<{mode:string}>('/api/auth/mode'),request<User>('/api/auth/me').catch(()=>null)]).then(([mode,u])=>{if(active){setAuthMode(mode.mode);setUser(u);if(u)setCsrf(u.csrf_token);setLoaded(true);}}).catch(e=>{if(active){setError(e.message);setLoaded(true);}});return()=>{active=false;};},[]);
 useEffect(()=>{if(user)void refresh();},[user]);
 async function login(identity:string){setError('');try{const u=await request<User>('/api/auth/demo?identity='+identity,'POST');setCsrf(u.csrf_token);setUser(u);}catch(e){setError((e as Error).message);}}
 async function logout(){try{await request('/api/auth/logout','POST');setUser(null);setCsrf('');setReport(null);setRuns([]);setAudit([]);}catch(e){setError((e as Error).message);}}
 async function exportReport(format:string){try{await download('/api/export/'+format+'?'+query(repository,branch,minutes));}catch(e){setError((e as Error).message);}}
 async function remove(run:Run){const reason=window.prompt('Export anything you need first. Why should this run be permanently removed?');if(!reason)return;try{await request('/api/runs/'+run.id,'DELETE',{reason});await refresh();}catch(e){setError((e as Error).message);}}
 if(!loaded)return <main><p role="status">Connecting to the triage workspace…</p></main>;
 if(!user)return <main className="login"><div className="eyebrow">ALAN VO · AI / DEVOPS</div><h1>CI Failure Triage</h1><p>Turn noisy CI failures into evidence you can prioritize, investigate and audit.</p><a className="button" href="/api/auth/login">Sign in with SSO</a>{authMode==='demo'&&<section className="panel"><h2>Local demonstration</h2><p>Sample identities are enabled only in explicit loopback demo mode.</p><div className="actions">{['analyst','reviewer','admin'].map(x=><button key={x} onClick={()=>login(x)}>Demo {x}</button>)}</div></section>}{error&&<p className="error" role="alert">{error}</p>}</main>;
 return <><header><div><div className="eyebrow">ALAN VO · AI / DEVOPS</div><h1>CI Failure Triage</h1></div><div className="identity"><span>{user.username} · {user.roles.join(', ')}</span><button className="secondary" onClick={logout}>Sign out</button></div></header><nav aria-label="Workspace">{['board','import','runs','analysis','audit'].map(x=><button key={x} aria-current={tab===x?'page':undefined} className={tab===x?'active':'secondary'} onClick={()=>setTab(x)} disabled={x==='import'&&!editable}>{x.charAt(0).toUpperCase()+x.slice(1)}</button>)}</nav><main>
 <section className="filters" aria-label="Report filters"><label>Repository<input placeholder="All repositories" value={repository} onChange={e=>setRepository(e.target.value)} maxLength={160}/></label><label>Branch<input placeholder="All branches" value={branch} onChange={e=>setBranch(e.target.value)} maxLength={160}/></label><label>Investigation minutes / failure<input type="number" min={0} max={480} value={minutes} onChange={e=>setMinutes(Math.min(480,Math.max(0,Number(e.target.value))))}/></label><button onClick={refresh} disabled={busy}>Apply / refresh</button></section>
 {error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Loading current evidence…</p>}
 {tab==='import'&&editable&&<ImportPanel onImported={refresh}/>}
 {tab==='board'&&report&&<><div className="metrics"><div><strong>{report.summary.runs}</strong> retained runs</div><div><strong>{report.summary.failure_groups}</strong> failure signatures</div><div><strong>{report.summary.failed_job_minutes}</strong> failed job minutes</div><div><strong>{report.summary.flaky_candidates}</strong> flakiness candidates</div></div><section className="panel"><div className="section-head"><h2>Prioritized failures</h2><div className="actions">{['json','csv','markdown'].map(x=><button className="secondary" key={x} onClick={()=>exportReport(x)}>Export {x.toUpperCase()}</button>)}</div></div><p>Sorted by failed job duration plus the investigation assumption. This estimate is not measured developer time. Signature boundaries preserve error codes and assertion values.</p><label>Triage filter<select value={status} onChange={e=>setStatus(e.target.value)}>{['all','new','investigating','resolved','ignored'].map(s=><option key={s}>{s}</option>)}</select></label><div className="table-wrap"><table><thead><tr><th>Failure / scope</th><th>Failures</th><th>Failed minutes</th><th>Estimated impact</th><th>Triage</th><th>Evidence</th></tr></thead><tbody>{report.groups.filter(g=>status==='all'||g.triage.status===status).map(g=><tr key={g.id}><td><strong>{g.job}{g.test&&' / '+g.test}</strong><p className="muted">{g.repository} · {g.workflow}</p><code>{g.canonical}</code>{g.flaky_candidate&&<span className="badge">Mixed commit outcomes</span>}</td><td>{g.failure_count}</td><td>{g.failed_job_minutes}</td><td>{g.estimated_impact_minutes} min</td><td>{g.triage.status}<small>{g.triage.owner||'Unassigned'}</small></td><td><button onClick={()=>setSelected(g)}>Inspect</button></td></tr>)}</tbody></table></div>{!report.groups.length&&<p className="empty">No failure groups in this sample. Import CI runs to start investigating.</p>}</section>{selected&&<GroupPanel key={selected.id+selected.triage.revision} group={selected} editable={editable} onSaved={refresh} onClose={()=>setSelected(null)}/>}<details className="panel"><summary>Interpretation limits</summary><ul>{report.limitations.map(x=><li key={x}>{x}</li>)}</ul></details></>}
 {tab==='runs'&&<section className="panel"><h2>Imported run history</h2><p>Deleting a run permanently removes its excerpts and removes it from analysis. Audit records remain. Export your report before applying retention.</p><div className="table-wrap"><table><thead><tr><th>Run / workflow</th><th>Repository / branch</th><th>Commit</th><th>Started</th><th>Jobs</th><th>Retention</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.external_id} / attempt {r.attempt}<small>{r.workflow}</small></td><td>{r.repository}<small>{r.branch}</small></td><td><code>{r.commit.slice(0,12)}</code></td><td>{r.started_at}</td><td>{r.job_count}</td><td>{user.roles.includes('admin')?<button className="danger" onClick={()=>remove(r)}>Delete run</button>:'Admin only'}</td></tr>)}</tbody></table></div>{!runs.length&&<p className="empty">No runs imported for these filters.</p>}</section>}
 {tab==='analysis'&&<AnalysisPanel repository={repository} branch={branch} editable={editable}/>}
 {tab==='audit'&&<section className="panel"><h2>Audit trail</h2><p>Latest 500 events, newest first. Up to 20,000 events are retained; further mutations then require an archived workspace.</p>{audit.map(a=><details key={a.id}><summary>{a.created_at} · {a.event} · {a.actor}</summary><p>Target: {a.target}</p><pre>{JSON.stringify(a.details,null,2)}</pre></details>)}{!audit.length&&<p>No mutations yet.</p>}</section>}
 </main><footer>Built by Alan Vo · <a href="mailto:alanvo@gmail.com">alanvo@gmail.com</a> · Deterministic evidence first; optional model advice.</footer></>;
}
